language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.0.1

    # The SDK version used to compile your project
    - android-21

notifications:
  email:
    - dmytro.kataryna@teamvoy.com
    - kataryna.dmytro@gmail.com
    on_success: always
    on_failure: change

script: ./gradlew assembleDebug
