language: android
android:
  components:

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extras
    - extra-google-m2repository
    - extra-android-m2repository

notifications:
  email:
    - dmytro.kataryna@teamvoy.com
    - kataryna.dmytro@gmail.com

before_script:
    - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a --skin WVGA800
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    - cd ./ReactiveCascade

script:
 - ./gradlew clean build connectedCheck
